version: '3'
services:
  forum:
    image: rustbb
    container_name: cnRust
    depends_on:
      - redis
    ports:
      - '4567:4567'
    environment:
      OSS_UPLOADS_BUCKET:
      OSS_UPLOADS_HOST:
      OSS_UPLOADS_PATH:
      OSS_DEFAULT_REGION:
    volumes:
      - ./data/nodebb:/var/lib/nodebb
    links:
      - redis
    restart: always

  redis:
    image: redis:alpine
    container_name: cnRust-redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
    restart: always
